### ISSUE TITLE
customize zsh when in nix-shell

### ISSUE THREAD

**Issue by safareli** [chisui/zsh-nix-shell#12]
### a bit off-topic question

Can you let's say change `➜ `  of zsh to something else only when it's running from nix-shell, so when you look at terminal you know if it's running in as part of nix-shell or not?

**Comment by chisui** [comment]
Since people use all kinds of themes and ways to construct their prompt this plugin can't change the prompt directly.

`nix-shell` itself sets `IN_NIX_SHELL=1` in the environment. You can use that to set the prompt accordingly. This plugin also exposes what the shell actually contains as well. The [readme hat a section on that](https://github.com/chisui/zsh-nix-shell#environment-info) with an example zsh theme that uses it.

**Comment by safareli** [comment]
thanks
