### ISSUE TITLE
How do you install this in NixOS

### ISSUE THREAD

**Issue by ryanpeach** [chisui/zsh-nix-shell#16]
Is it in nixpkgs?

The git clone won't work because it puts it in /nix/store/*/share/oh-my-zsh/...

**Comment by chisui** [comment]
I plan to publish this to nixpkgs, but I don't quite what the best approach would be, since I don't want to force users to use oh-my-zsh or any specific plugin manager for zsh. Ideas are very welcome!

For now I use the [`ZSH_CUSTOM` directory](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#using-another-customization-directory) to manage my external plugins and themes. I could document my current setup somewhere if you are interested.

**Comment by ryanpeach** [comment]
Yeah document an initial recommendation, maybe I can nixpkgs it :)

**Comment by dR3b** [comment]
Please create a "release" tar.gz, so I can use it very easily with "home-manager [1]" :+1: 
```bash
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    plugins = [
      {
        name = "zsh-nix-shell";
        src = pkgs.fetchFromGitHub {
          owner = "chisui";
          repo = "zsh-nix-shell";
          rev = "v0.1.0";
          sha256 = "xxxxxxxxxxxx";
        };
      }
    ];
  };
```
[1] https://rycee.gitlab.io/home-manager/options.html#opt-programs.zsh.plugins

**Comment by chisui** [comment]
@dR3b Done.

    sha256 = "0snhch9hfy83d4amkyxx33izvkhbwmindy0zjjk28hih1a9l2jmx";

**Comment by dR3b** [comment]
Danke!

**Comment by chisui** [comment]
Added stuff discussed here to the readme.
