### ISSUE TITLE
A better way

### ISSUE THREAD

**Issue by Root-Time** [chisui/zsh-nix-shell#41]
## A better way

there is a better way then using this plugin:

`nix-shell --command zsh ...`

you can add an alias in your nix config or other config.
`nix-shell = "nix-shell --command zsh"`

My Issue / Question is why is this plugin better then just using this method above.

**Comment by chisui** [comment]
Feel free to use an `alias` if you feel that it's *a better way*.

Some things that this plugin provides that an `alias` wont:

* `zsh` doesn't have to be in `PATH` inside of the `nix-shell` environment
* completions of derivations are added to `FPATH`
* `--command` and `--pure` still work as expected.
* works with `direnv` and `lorri`
* The name of loaded packages or derivation are exposed through an environment variable and can be used in the shell prompt

Since `nix-shell` modifies `PATH` a more robust alias might be `nix-shell --command "$(readlink -f $(where zsh))"` or if you write it in your nix config: `nix-shell --command ${pkgs.zsh}/bin/zsh`.
